import React, { useState, useEffect } from "react";
import {
  X,
  Printer,
  Copy,
  Check,
  FileText,
  Stethoscope,
  Sparkles,
  AlertCircle,
  Calendar,
} from "lucide-react";
import { ClinicalVisitSummary, FamilyMember, VitalRecord } from "../types";
import { copyTextToClipboard } from "../utils/medicalUtils";

interface VisitPrepSheetModalProps {
  isOpen: boolean;
  onClose: () => void;
  member: FamilyMember;
  vitals: VitalRecord[];
}

export const VisitPrepSheetModal: React.FC<VisitPrepSheetModalProps> = ({
  isOpen,
  onClose,
  member,
  vitals,
}) => {
  const [copied, setCopied] = useState(false);
  const [chiefComplaint, setChiefComplaint] = useState(
    member.conditions[0] || "Health status review & routine follow-up"
  );
  const [summary, setSummary] = useState<ClinicalVisitSummary | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Latest vitals for this member
  const memberVitals = vitals.filter((v) => v.memberId === member.id);
  const latestBp = memberVitals.find((v) => v.type === "bp");
  const latestSugar = memberVitals.find((v) => v.type === "sugar");

  const generateSummary = async () => {
    setIsLoading(true);
    try {
      const res = await fetch("/api/doctor/generate-summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          patientProfile: {
            name: member.name,
            age: member.age,
            gender: member.gender,
            memberType: member.memberType,
            conditions: member.conditions,
            medications: member.medications,
            allergies: member.allergies,
          },
          vitals: {
            bp: latestBp ? { systolic: latestBp.systolic, diastolic: latestBp.diastolic } : null,
            sugar: latestSugar ? { value: latestSugar.sugarValue } : null,
          },
          chiefComplaint,
        }),
      });
      const data = await res.json();
      setSummary(data);
    } catch (err) {
      console.error("Generate summary error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      generateSummary();
    }
  }, [isOpen, member.id]);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = async () => {
    if (!summary) return;
    const text = `CLINICAL VISIT INTAKE & HANDOFF NOTE
Generated by PersonalDoc for: ${member.name} (Age: ${member.age}, Sex: ${member.gender})
Date: ${new Date().toLocaleDateString()}

CHIEF COMPLAINT:
${chiefComplaint}

HISTORY OF PRESENT ILLNESS (HPI):
${summary.historyOfPresentIllness}

CURRENT VITALS ON RECORD:
- Blood Pressure: ${latestBp ? `${latestBp.systolic}/${latestBp.diastolic} mmHg` : "Not recorded"}
- Blood Sugar: ${latestSugar ? `${latestSugar.sugarValue} mg/dL` : "Not recorded"}

CURRENT MEDICATIONS:
${member.medications.join(", ") || "None"}

ALLERGIES:
${member.allergies.join(", ") || "No known drug allergies (NKDA)"}

QUESTIONS PREPARED FOR PHYSICIAN:
${summary.recommendedDoctorQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

DIFFERENTIALS & WORKUP CONSIDERATIONS:
${summary.suggestedWorkup.join(", ")}
`;

    if (await copyTextToClipboard(text)) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white w-full max-w-3xl rounded-xl shadow-xl border border-slate-200 overflow-hidden my-8">
        
        {/* Modal Top Controls (Hidden on print) */}
        <div className="px-5 py-3.5 bg-white border-b border-slate-100 flex items-center justify-between gap-3 print:hidden">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-slate-100 text-[#176b4d] flex items-center justify-center border border-slate-200">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-xs sm:text-sm">
                Clinical Visit Intake Sheet
              </h3>
              <p className="text-[11px] text-slate-500">
                Pre-appointment handoff document for your primary care physician
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyText}
              className="px-2.5 py-1.5 rounded-lg bg-white border border-slate-200 text-slate-700 text-xs font-medium hover:bg-slate-50 flex items-center gap-1.5 transition-colors cursor-pointer shadow-2xs"
              title="Copy formatted clinical note"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
              <span className="hidden sm:inline">{copied ? "Copied" : "Copy"}</span>
            </button>
            <button
              onClick={() => {
                if (!summary) return;
                const text = `CLINICAL VISIT INTAKE & HANDOFF NOTE\nGenerated by PersonalDoc for: ${member.name} (Age: ${member.age}, Sex: ${member.gender})\nDate: ${new Date().toLocaleDateString()}\n\nCHIEF COMPLAINT:\n${chiefComplaint}\n\nHISTORY OF PRESENT ILLNESS:\n${summary.historyOfPresentIllness}\n\nCURRENT VITALS:\n- Blood Pressure: ${latestBp ? `${latestBp.systolic}/${latestBp.diastolic} mmHg` : "Not recorded"}\n- Blood Sugar: ${latestSugar ? `${latestSugar.sugarValue} mg/dL` : "Not recorded"}\n\nCURRENT MEDICATIONS:\n${member.medications.join(", ") || "None"}\n\nALLERGIES:\n${member.allergies.join(", ") || "NKDA"}\n\nQUESTIONS PREPARED FOR PHYSICIAN:\n${summary.recommendedDoctorQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}\n`;
                const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = `Doctor_Prep_${member.name.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.txt`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="px-2.5 py-1.5 rounded-lg bg-white border border-slate-200 text-slate-700 text-xs font-medium hover:bg-slate-50 flex items-center gap-1.5 transition-colors cursor-pointer shadow-2xs"
              title="Download text file"
            >
              <FileText className="w-3.5 h-3.5 text-slate-500" />
              <span className="hidden sm:inline">Export</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg bg-[#176b4d] text-white text-xs font-semibold hover:bg-[#12583f] flex items-center gap-1.5 shadow-xs transition-colors cursor-pointer"
              title="Print or Save as PDF"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* The Printable Clinical Summary Sheet */}
        <div id="printable-prep-sheet" className="p-6 sm:p-8 space-y-5 print:p-0">
          
          {/* Header of the sheet */}
          <div className="border-b border-slate-900 pb-3 flex justify-between items-end">
            <div>
              <span className="text-[10px] font-mono uppercase tracking-widest text-[#176b4d] font-bold">
                PersonalDoc Clinical Summary
              </span>
              <h2 className="text-xl font-bold text-slate-900 font-serif mt-0.5">
                Patient Pre-Consultation Intake Record
              </h2>
            </div>
            <div className="text-right text-[11px] text-slate-500 font-mono">
              <div>Date: {new Date().toLocaleDateString()}</div>
              <div>EMR: #PD-{member.id.toUpperCase()}</div>
            </div>
          </div>

          {/* Demographics row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50/80 p-3 rounded-lg border border-slate-200 text-xs">
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-semibold">Patient Name</span>
              <span className="font-bold text-slate-900">{member.name}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-semibold">Age / Gender</span>
              <span className="font-semibold text-slate-800">{member.age} yrs • {member.gender}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-semibold">Role</span>
              <span className="font-semibold text-slate-800 capitalize">{member.relationship}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-semibold">Blood Group</span>
              <span className="font-semibold text-slate-800">{member.bloodType || "O+"}</span>
            </div>
          </div>

          {/* Loading state */}
          {isLoading && (
            <div className="p-10 text-center text-xs text-slate-500 flex flex-col items-center gap-2">
              <span className="w-5 h-5 rounded-full border-2 border-[#176b4d] border-t-transparent animate-spin"></span>
              <span>Synthesizing clinical intake sheet for in-person physician...</span>
            </div>
          )}

          {summary && !isLoading && (
            <div className="space-y-4 text-xs text-slate-800">
              
              {/* Chief Complaint & HPI */}
              <div>
                <h4 className="font-semibold text-slate-900 uppercase tracking-wider text-[11px] mb-1.5 border-b border-slate-200 pb-1">
                  1. Chief Complaint & History of Present Illness (HPI)
                </h4>
                <p className="leading-relaxed text-slate-700 bg-slate-50/60 p-3 rounded-lg border border-slate-100">
                  {summary.historyOfPresentIllness}
                </p>
              </div>

              {/* Vitals Snapshot */}
              <div>
                <h4 className="font-semibold text-slate-900 uppercase tracking-wider text-[11px] mb-1.5 border-b border-slate-200 pb-1">
                  2. Recent Home Vitals Record
                </h4>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                  <div className="p-2.5 rounded-lg border border-slate-200 bg-white">
                    <span className="text-[10px] text-slate-400 block">Recent Blood Pressure</span>
                    <span className="font-bold text-sm text-slate-900 font-mono">
                      {latestBp ? `${latestBp.systolic}/${latestBp.diastolic} mmHg` : "N/A"}
                    </span>
                  </div>
                  <div className="p-2.5 rounded-lg border border-slate-200 bg-white">
                    <span className="text-[10px] text-slate-400 block">Recent Glucose</span>
                    <span className="font-bold text-sm text-slate-900 font-mono">
                      {latestSugar ? `${latestSugar.sugarValue} mg/dL` : "N/A"}
                    </span>
                  </div>
                  <div className="p-2.5 rounded-lg border border-slate-200 bg-white">
                    <span className="text-[10px] text-slate-400 block">Heart Rate</span>
                    <span className="font-bold text-sm text-slate-900 font-mono">
                      {latestBp?.heartRate ? `${latestBp.heartRate} bpm` : "72 bpm"}
                    </span>
                  </div>
                </div>
              </div>

              {/* Current Meds & Allergies */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <h4 className="font-semibold text-slate-900 uppercase tracking-wider text-[11px] mb-1.5 border-b border-slate-200 pb-1">
                    3. Current Medications
                  </h4>
                  {member.medications.length > 0 ? (
                    <ul className="list-disc list-inside space-y-1 text-slate-700">
                      {member.medications.map((m, idx) => (
                        <li key={idx}>{m}</li>
                      ))}
                    </ul>
                  ) : (
                    <span className="text-slate-400 italic">No daily medications</span>
                  )}
                </div>

                <div>
                  <h4 className="font-semibold text-slate-900 uppercase tracking-wider text-[11px] mb-1.5 border-b border-slate-200 pb-1">
                    4. Known Drug Allergies
                  </h4>
                  <span className="text-rose-700 font-semibold">
                    {member.allergies.join(", ") || "No Known Drug Allergies (NKDA)"}
                  </span>
                </div>
              </div>

              {/* Questions for the Doctor */}
              <div>
                <h4 className="font-semibold text-slate-900 uppercase tracking-wider text-[11px] mb-1.5 border-b border-slate-200 pb-1">
                  5. High-Yield Questions Prepared for Physician
                </h4>
                <ol className="list-decimal list-inside space-y-1 text-slate-700">
                  {summary.recommendedDoctorQuestions.map((q, idx) => (
                    <li key={idx} className="leading-snug">{q}</li>
                  ))}
                </ol>
              </div>

              {/* Red flags */}
              <div className="p-2.5 bg-amber-50/80 rounded-lg border border-amber-200/80 text-[11px] text-amber-900">
                <strong>Emergency Warning:</strong> If experiencing acute chest pressure, dyspnea, speech difficulty, or severe neurological deficits, immediately dial emergency services (112 / 108 in India).
              </div>

            </div>
          )}

        </div>

      </div>
    </div>
  );
};
